catalog/urls.py
from django.urls import path, re_path
from . import views


urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^books/$', views.BookListView.as_view(), name='books'),
    # re_path(r'^book/(?P<pk>\d+)$', views.book_detail_view, name='book-detail'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    re_path(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    re_path(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)), 
    path('accounts/', include('django.contrib.auth.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid

class Language(models.Model):
    language = models.CharField(max_length=50, unique=True,  help_text='Введите язык на котором напечатана книга(Русскийб анлийскийб японский и тд)')

    def __str__(self):
        return self.language
    
    def get_absolute_url(self):
        return reverse('language-detail', args=[str(self.id)] )

class Genre(models.Model):
    name = models.CharField(max_length=20, help_text='Enter a book genre(e.g. French poetry, Science fantastic etc.)')

    def __str__(self):
        return self.name
    
class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(verbose_name='Описание', max_length=1000, help_text='Введи описание книги')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Введите жанр книги')
    language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])
    
    def display_genre(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ])
    display_genre.short_description = 'Жанр'
    # short_description указывает как будет называться данная функция в админ панели если мы ее укажем показывать на панели в admin.py
    class Meta:
        ordering = ['title']    

class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True,default=uuid.uuid4, help_text='ID для каждой книги индивидуален в библиотеке' )
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    

    LOAN_STATUS = (
        ('m', 'Maintenance(Техническое обслуживание)'),
        ('o', 'On loan(На руках)'),
        ('a', 'Available(Доступна для бронирования)'),
        ('r', 'Reserved(Зарезервирована)')
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, default='m', blank=True, help_text='Доступность экземпляра на данный момент')

    class Meta:
        ordering = ['-due_back']

    def __str__(self):
        return '{0} - {1}'.format(self.id,self.book.title)
    
    def get_absolute_url(self):
        return reverse('BookInstance-detail', args = [str(self.id)])
    
    # def display_book(self):
    #     return self.book
    # display_book.short_description = 'Название'
    
class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])
    
    def __str__(self):
        return '{0} {1}'.format(self.first_name, self.last_name)
    
    class Meta:
        ordering = ['last_name']

catalog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Book, BookInstance, Author, Genre

def index(request):
    num_books = Book.objects.all().count()
    num_authors = Author.objects.all().count()
    num_book_inctances = BookInstance.objects.all().count()
    num_book_inctances_available = BookInstance.objects.filter(status__exact='a').count()
    num_with_a = Book.objects.filter(title__contains='и' ).count()
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1
    return render(request, 'index.html', context={
        'num_books':num_books, 
        'num_authors': num_authors,
        'num_book_inctances':num_book_inctances,
        'num_book_inctances_available': num_book_inctances_available,
        'num_with_a':num_with_a,
        'num_visits':num_visits
    })

class BookListView(generic.ListView):
    model = Book
    # paginate_by = 3

'''def book_detail_view(request,pk):
    try:
        book_id=Book.objects.get(pk=pk)
    except Book.DoesNotExist:
        raise Http404("Book does not exist")

    #book_id=get_object_or_404(Book, pk=pk)

    return render(
        request,
        'catalog/book_detail.html',
        context={'book':book_id,}
    )'''

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author

class AuthorDetailView(generic.DetailView):
    model = Author

catalog/templates/base_template.html
<!doctype html>
<html lang="en">
  <head>
    {% block title %}<title>Local Library</title>{% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Добавление дополнительного статического CSS файла -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            <ul class="sidebar-nav">
              <li><a href="{% url 'index' %}">Home</a></li>
              <li><a href="{% url 'books' %}">All books</a></li>
              <li><a href="{% url 'authors' %}">All authors</a></li>
            </ul>
          {% endblock %}
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
      </div>
    </div>
  </body>
</html>

catalog/templates/catalog/author_detail.html
{% extends 'base_template.html' %}

{% block content %}
<h1>{{author.first_name}} {{author.last_name}}</h1>
<div style="margin-left:20px;margin-top:20px">
    <h1>Books</h1>

    {% for book in author.book_set.all %}
    <h3>
        <a href="{% url 'book-detail' book.id %}">{{book.title}}</a>
    </h3>


    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends 'base_template.html' %}

{% block content %}
<h1>Author List</h1>
{% if author_list %}
    <ul>
        {%for author in author_list%}
        <li>
            <a href="{{author.get_absolute_url}}">{{author.first_name}} {{author.last_name}}</a>
        </li>
        {% endfor %}
    </ul>

{% else %}
<h1>There aren't any authors</h1>
{% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_template.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.id %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_template.html" %}

{% block content %}
    <h1>Book List</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/index.html
{% extends "base_template.html" %}
{%block title%} <title>Home Page</title>
{%endblock%}
{% block content %}
<h1>Local Library Home</h1>

  <p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed as a tutorial example on the Mozilla Developer Network.</p>

<h2>Dynamic content</h2>

  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_book_inctances }}</li>
    <li><strong>Copies available:</strong> {{ num_book_inctances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Titles with 'a':</strong> {{ num_with_a }}</li>
    
  </ul>
  You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{%
    else %} times{% endif %}.
{% endblock %}